[package]
name = "donft-collection-factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
donft-bundle = { path = "../donft-bundle", features = ["factory-wasm"] }

